### ISSUE TITLE
Document for the Capcom Commando hardware

### ISSUE THREAD

**Issue by joeyjyliu** [fredrequin/fpga_1943#1]
Hi, I wonder if you can point me to the hardware spec of the capcom commando hardware which I think it's the one runs the original 1943. I just finished a recreation of the original pacman with the Z80 cpu, eeprom, sram, atmega 2560 and a bunch of 74HC for the memory mapping. For pacman there is a lot of details out there but I can't google much useful information about the 1943 for example the memory map the VRAM and the sound. I know MAME has the implementation but if you know there is some kind of other documents available please point me to that. Thanks a lot.

**Comment by jotego** [comment]
I would kindly suggest you to do a different game as I have the Commando core rather advanced right now.

**Comment by joeyjyliu** [comment]
Cool. Just for my curiosity/edification could you point me to the spec of the commando machine?

**Comment by jotego** [comment]
Absolutely. You have it [here](https://www.arcade-museum.com/game_detail.php?game_id=7376). If you are interested in old CAPCOM games and want to collaborate I am actively doing one after another right now. With 1942, Ghosts'n Goblins and 1943 already done (including sound). You can check out my repo [here](https://github.com/jotego/jt_gng).
